### ISSUE TITLE
Suggestion for FAQ

### ISSUE THREAD

**Issue by KujawinskiLaboratory** [biocore/mmvec#132] opened 2020-04-26 16:48 UTC
I have just started to use the mmvec tool and have found that it will be useful. As I am not familiar with qiime2, it took me a while to get that up and running (with the added challenge that I am running a Windows environment and needed to set it up through docker). Now that I have qiime2 running with the mmvec plugin, I realize that there are some subtleties that I did not understand at first. Honestly, I am not sure I understand them all yet. 
For the FAQ, my first suggestion is the question has to do with the standalone script versus the qiime2 interface. I _think_ the standalone script is run as follows:
`mmvec paired-omics`...
while the qiime interface is:
`qiime mmvec paired-omics`...
If I am right, perhaps this distinction can be added to the first point in the FAQ. It took me a while going through the different examples to see that the syntax is slightly different. 
A second, related suggestion, would be to annotate this file:
https://github.com/biocore/mmvec/blob/master/examples/soils/run.sh
so that it is clear that the script has two different pieces, one for the stand-along option and one for the qiime2 interface. Also, this would be even clearer if the same set of variables is passed in both examples to help people connect the dots.
Thanks for developing this tool. I think it will be quite useful.

**Comment by KujawinskiLaboratory** [comment] 2020-05-07 18:59
I have one more question/comment on the readme file, for the section on the qiime2 plugin. 
The text describes running mmvec as this:
```
qiime mmvec paired-omics \
	--i-microbes otus_nt.qza \
	--i-metabolites lcms_nt.qza \
	--p-learning-rate 1e-3 \
	--o-conditionals ranks.qza \
	--o-conditional-biplot biplot.qza
```
The text goes on to talk about two files in a results folder (conditional_biplot.qza and conditionals.qza). When I run mmvec, I do not get a results folder at all, and when I try to set the output directory using:
`--output-dir my_results_here`
I get an empty folder.
Does this line: `--o-conditionals ranks.qza` produce a conditionals file that is called ranks.qza (and hence, not put the file into a results folder as the subsequent paragraph indicates)?

**Comment by mortonjt** [comment] 2020-05-07 19:55
That is strange behavior. Are there any errors when you run the above comment (i.e. can you pass in the `--verbose` flag?).  I'm wondering if mmvec is installed correctly.

**Comment by KujawinskiLaboratory** [comment] 2020-05-07 20:09
I don't get any errors with the `--verbose ` flag (though I get lots of warnings about things being deprecated).
I am running qiime2/2020.2 through a docker container on a Windows 10 machine. I have a limited knowledge of docker, and no prior knowledge of qiime2 or its plugins. Hence, it is entirely possible this has not been installed correctly.

After my initial post, I noticed that this: 
```
qiime mmvec paired-omics \
	--i-microbes otus_nt.qza \
	--i-metabolites lcms_nt.qza \
	--p-learning-rate 1e-3 \
	--o-conditionals ranks.qza \
	--o-conditional-biplot biplot.qza \
        --output-dir myFolder
```
Makes an empty folder, and puts ranks.qza and bioplot.qza into the working directory.

While this:
```
qiime mmvec paired-omics \
	--i-microbes otus_nt.qza \
	--i-metabolites lcms_nt.qza \
	--p-learning-rate 1e-3 \
        --output-dir myFolder
```

will make myFolder and put conditional_bioplot.qza and conditionals.qza in the folder

**Comment by mortonjt** [comment] 2020-05-07 20:14
Ok, if I am reading this correctly you are able to get results.  But specifying both `--output-dir` and `--o-conditionals` / `--o-conditional-biplot` gives you an empty folder.  @ebolyen, is this expected behavior for qiime2?

If you only specify the `--output-dir`, that will put all of those `--o-conditionals` / `--o-conditional-biplot` results into that folder (`--output-dir` is primarily a convenience parameter)

**Comment by KujawinskiLaboratory** [comment] 2020-05-07 20:16
Correct - your description matches what I see.

**Comment by ebolyen** [comment] 2020-05-07 20:20
Oh interesting. The empty folder is not really intentional, but I suppose it isn't unexpected either. The job of `--output-dir` is to catch any unspecified outputs for when you are feeling lazy. So it is just creating the directory under the assumption that surely something will be written inside of it someday (it isn't in control of what gets written, just where to put the leftovers).

**Comment by mortonjt** [comment] 2020-06-19 17:45
Hi @KujawinskiLaboratory , it looks like your question has been answered here, so I'm going to close this issue. If you run into additional issues, feel free to follow up.

**Closed by mortonjt** 2020-06-19 17:45 UTC
